#!/usr/bin/perl
use strict;
use warnings;

# dbbolton
# danielbarrettbolton@gmail.com

my $ac_status = (split(/ /,`acpi -a`))[2];
my $battery_status = (split(',',(split(/ /,`acpi -b`))[2]))[0];

if ($ac_status =~ /on-line/) {
    print "Running on AC power... using the performance governor\n";
    system('cpufreq-set --cpu 0 --governor performance') == 0
        or die "Setting governor for CPU 0 failed: $?";
    print "Finished with CPU 0.\n";
    system('cpufreq-set --cpu 1 --governor performance') == 0
        or die "Setting governor for CPU 1 failed: $?";
    print "Finished with CPU 1.\n";

} elsif ($battery_status =~ /Discharging/ || $ac_status =~ /off-line/ ) {
    print "Running on Battery power... using the powersave governor\n";
    system('cpufreq-set --cpu 0 --governor powersave') == 0
        or die "Setting governor for CPU 0 failed: $?";
    print "Finished with CPU 0.\n";
    system('cpufreq-set --cpu 1 --governor powersave') == 0
        or die "Setting governor for CPU 1 failed: $?";
    print "Finished with CPU 1.\n";
} else {
    print "Power source unknown... using the ondemand governor\n";
    system('cpufreq-set --cpu 0 --governor ondemand') == 0
        or die "Setting governor for CPU 0 failed: $?";
    print "Finished with CPU 0.\n";
    system('cpufreq-set --cpu 1 --governor ondemand') == 0
        or die "Setting governor for CPU 1 failed: $?";
    print "Finished with CPU 1.\n";
}

print "cpu-gov is finished.\n";
