#!/usr/bin/env perl
use strict;
use warnings;

my $name = &letter;

for ( 0 .. 11 ) {
    my $do = int( rand(2) );
    if ($do) {
        $name .= &number;
    }
    else {
        $name .= &letter;
    }
}

print "Inbox name:\t$name\n" .
      "Inbox URL: \thttp://$name.mailinator.com/\n";

sub letter {
    my $out = chr( int( rand(26) ) + 97 );
}

sub number {
    my $out = int( rand(10) );
}
