#!/usr/bin/perl
use strict;

# dbbolton
# danielbarrettbolton at gmail

eval {
    require Net::Twitter;
    Net::Twitter->import();
};

if ( $@ ) {
    print "You need to install 'Net::Twitter'. The Debian package name is:\n\nlibnet-twitter-perl\n";
    exit 1;
}

unless (@ARGV) {
    &help;
    exit;
}

my $nt;
my $opt;
my $password;
my $status_name;
my $message;
my $user;

for ( my $argc = 0; $argc <= @ARGV; $argc++) {
        $opt = $ARGV[$argc];
        $opt =~ s/^--//; # Get rid of 2 dashes
        $opt =~ s/^-//; # Get rid of 1 dash
        $opt =  substr($opt,0,1); # cut the first char
        if ( $opt =~ /u/i ) {
            $user = $ARGV[++$argc];
        }
        elsif ( $opt =~ /p/i ) {
            $password = $ARGV[++$argc];
        }
        elsif ( $opt =~ /h/i ) {
            help();
        }
        elsif ( $opt =~ /s/i ) {
            $status_name = $ARGV[++$argc];
            &get_status;
        }
        elsif ( $opt =~ /t/i ) {
            $message = $ARGV[++$argc];
            &tweet;
        }
        elsif ( $opt =~ /^\s*$/ ) {
           next;
        }

        else {
            print "Bad option: '$opt'";
            &help();
        }
}

#############################################################################
# Optionally provide default login info here

sub login {
    $user = 'USERNAME_LINE_61' unless $user;
    $password = 'PASSWORD_LINE_62' unless $password;

    $nt = Net::Twitter->new(
    traits   => [qw/API::REST/],
    username => $user,
    password => $password
    );
}
#############################################################################

sub get_status {
    &login;
    my $status = $nt->show_user($status_name)->{status}->{text};
    print "$status_name" . "'s status:\n\n$status\n";
} # end &get_status

sub tweet {
    &login;
    my $result = $nt->update( $message );
    $status_name = $user;
    &get_status;
} # end &tweet

sub help {
    print <<EOF;
Options:
-u 'name'       login as "name"
-p 'text'       login password
-t 'message'    tweet "message"
-s 'user'       show the latest tweet from "user"
EOF
} # end &help
