#!/bin/sh
os=$(awk '{ print "\n"$1, $2, $3}' /etc/issue)
un=$(uname -s -r -m)
cpu=$(grep -m1 name /proc/cpuinfo | awk '{print $4,$5,$6,$7,$8,$9}')

echo
echo "OS:     " $os
echo "Kernel: " $un
echo "WM:     " $DESKTOP_SESSION
echo "CPU:    " $cpu
echo
scrot -cd 3

